version: '3.8'


services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: twitch
      MYSQL_ROOT_PASSWORD: secret
      TZ: UTC
    volumes:
      # connect the local volume mysql-local to the container volume /var/lib/mysql
      - mysql-local:/var/lib/mysql
    # connect local port 3306 to the container port 3306
    ports:
      - 3306:3306


# permanent storage of data.
# setting up the local storage for the mysql database.
volumes:
  mysql-local: